# Generated by Django 5.0.6 on 2024-06-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_play_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(related_name="plays", to="theatre.actor"),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                related_name="associated_plays", to="theatre.genre"
            ),
        ),
    ]
